/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TabChar123FilenameChar125RouteImport } from './routes/$tab.{-$filename}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabChar123FilenameChar125Route =
  TabChar123FilenameChar125RouteImport.update({
    id: '/$tab/{-$filename}',
    path: '/$tab/{-$filename}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tab/{-$filename}': typeof TabChar123FilenameChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$tab/{-$filename}': typeof TabChar123FilenameChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tab/{-$filename}': typeof TabChar123FilenameChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$tab/{-$filename}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$tab/{-$filename}'
  id: '__root__' | '/' | '/$tab/{-$filename}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabChar123FilenameChar125Route: typeof TabChar123FilenameChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tab/{-$filename}': {
      id: '/$tab/{-$filename}'
      path: '/$tab/{-$filename}'
      fullPath: '/$tab/{-$filename}'
      preLoaderRoute: typeof TabChar123FilenameChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabChar123FilenameChar125Route: TabChar123FilenameChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
