/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { faker } from '@faker-js/faker';
import { http, HttpResponse } from 'msw';

faker.seed(1);

const fake = {
  version: () =>
    `${faker.number.int({ min: 0, max: 1 })}.${faker.number.int({ min: 0, max: 9 })}.${faker.number.int({ min: 0, max: 9 })}`,

  files: () => [
    'nfqws2.conf',
    'user.list',
    'exclude.list',
    'auto.list',
    'ipset.list',
    'ipset_exclude.list',
    'nfqws2.log',
  ],

  fileContent: (filename) =>
    `# ${filename}
# generated by faker

${faker.lorem.paragraphs({ min: 1, max: 3 })}
`,

  actionOutput: (cmd) => [
    `${cmd}: ${faker.helpers.arrayElement(['OK', 'DONE'])}`,
  ],
};

export const handlers = [
  http.post('/index.php', async ({ request }) => {
    const fd = await request.formData();
    const cmd = String(fd.get('cmd') ?? '');

    switch (cmd) {
      case 'filenames': {
        /**
         * @type {FilenamesResponse}
         */
        const body = {
          status: 0,
          files: fake.files(),
          service: faker.datatype.boolean(),
          nfqws2: true,
          version: fake.version(),
        };
        return HttpResponse.json(body);
      }

      case 'filecontent': {
        const filename = String(fd.get('filename') ?? '');
        /**
         * @type {FileContentResponse}
         */
        const body = {
          status: 0,
          filename,
          content: fake.fileContent(filename),
        };
        return HttpResponse.json(body);
      }

      case 'filesave': {
        const filename = String(fd.get('filename') ?? '');
        /**
         * @type {FileSaveResponse}
         */
        const body = {
          status: faker.helpers.arrayElement([0, 0, 0, 1]), // иногда ошибка
          filename,
        };
        return HttpResponse.json(body);
      }

      case 'fileremove': {
        const filename = String(fd.get('filename') ?? '');
        /**
         * @type {FileRemoveResponse}
         */
        const body = {
          status: 0,
          filename,
        };
        return HttpResponse.json(body);
      }

      case 'restart':
      case 'stop':
      case 'start':
      case 'upgrade': {
        /**
         * @type {ActionResponse}
         */
        const body = {
          status: 0,
          output: fake.actionOutput(cmd),
        };
        return HttpResponse.json(body);
      }

      case 'logout': {
        /**
         * @type {LogoutResponse}
         */
        const body = { status: 0 };
        return HttpResponse.json(body);
      }

      default:
        return new HttpResponse(null, { status: 405 });
    }
  }),
];
